### ISSUE TITLE
How can i make use of dayjs plugins?

### ISSUE THREAD

**Issue by izshreyansh** [Juceztp/vue-dayjs#1]
Hey there,

Can someone please assist me on how can i make use if dayjs plugins like [Relative Time](https://day.js.org/docs/en/display/from-now) with this library?

**Comment by matschik** [comment]
You don't need to use this vue plugin, just use this code:

./myDayjsPlugin.js
```js
import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';

dayjs.extend(relativeTime);

export default {
  install(Vue) {
    Vue.prototype.$dayjs = dayjs
  },
};
```

./main.js
```js
import Vue from "vue"
import dayjsPlugin from "./myDayjsPlugin.js"

Vue.use(dayjsPlugin)
```

**Comment by izshreyansh** [comment]
Thanks so much.
Shall i add this on docs?

**Comment by matschik** [comment]
Which docs ? It's just JavaScript, do what you want :)

**Comment by Juceztp** [comment]
Updated docs :)
